### ISSUE TITLE
Unable to upload project using custom building blocks

### ISSUE THREAD

**Issue by X2431** [openblockcc/openblock-gui#21]
### Expected Behavior

After the project is uploaded, continuing to customize the blocks should be successful

### Actual Behavior

Click error

### Steps to Reproduce

1. Click "Make a Block"
2. Set any name
3. Click Save to local
4. Click upload from computer
5. Click again on the "Make a Block"
6. Set any name

the results are:

![image](https://user-images.githubusercontent.com/42490553/153800987-d2520aea-68de-4a7f-b4b9-4741d3db2ab8.png)

**Comment by zhengyangliu** [comment]
I can't reproduce your error, need you to provide more proof like screen recording.
![image](https://user-images.githubusercontent.com/10896145/156752288-b4ea81a5-8fb6-4d32-aea0-92e255a0095d.png)

**Comment by zhengyangliu** [comment]
I will find out what cause this error. There is a temp solution. You can creat a new sprite and select it then switch back, the blocks will be refreshed.

**Comment by ircbloqcc** [comment]
yes, we need to switch to costumes tab or sound tab, then came back to code tab, this will get refreshed.

https://user-images.githubusercontent.com/86342573/156754637-04ebda75-cace-4154-8185-7a9d341147ef.mp4
