### ISSUE TITLE
How to Add New Sprite?

### ISSUE THREAD

**Issue by PatelManav20** [openblockcc/openblock-gui#22]
I have tried converting .svg file into MD5 Hash but it is not working.

I have also tried uploading .svg file onto scratch website and using that MD5 hash but it is not working.

Please provide a solution.

![sprite](https://user-images.githubusercontent.com/85221629/155463807-d2ee702c-51ee-4610-bd2e-ed76e3f132ce.PNG)

![not working](https://user-images.githubusercontent.com/85221629/156164289-2d82072c-0a7b-4c66-8aa2-5d2758d9e03a.PNG)

**Comment by zhengyangliu** [comment]
You need F12 to see the detail of this error.
